import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./provides";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen w-screen rainbow-mesh p-6">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
